name: Generate Spider-Man SVG Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests svgwrite cairosvg

      - name: Generate SVG Graph
        run: |
          python generate_spiderman_svg.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/spiderman-contribution-graph.svg
          git commit -m "🕷️ Update Spider-Man contribution graph"
          git push
